name: 'release'

on:
    push:
        branches:
            - 'master'

jobs:
    release:
        name: 'Release'
        runs-on: 'ubuntu-latest'

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: 'Install pnpm'
              uses: pnpm/action-setup@v4

            - name: 'Install Dependencies'
              run: pnpm install --frozen-lockfile

            - name: 'Build & test'
              run: |
                  pnpm test
                  pnpm build

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'latest'
                  title: 'Release Build'
                  prerelease: false
                  files: |
                      LICENSE.txt
                      *.tar.gz
                      build/*
