name: 'release'

on:
    push:
        branches:
            - 'master'

jobs:
    release:
        name: 'Release'
        runs-on: 'ubuntu-latest'

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: 'Setup Bun'
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: 'Install Dependencies'
              run: bun install

            - name: 'Build & test'
              run: bun run build

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'latest'
                  title: 'Release Build'
                  prerelease: false
                  files: |
                      LICENSE.txt
                      *.tar.gz
                      build/*
